import "./forEach/forEachTest.js";
import "./head/headTest.js";
import "./eq/eqTest.js"
import "./isEmpty/isEmptyTest.js";
import "./reduce/reduceTest.js";
import "./uncons/unconsTest.js";
import "./max/maxTest.js";
import "./max/safeMaxTest.js";
import "./min/minTest.js";
import "./min/safeMinTest.js";
import "./foldr/foldrTest.js";
import "./show/showTest.js";
